name: Check format

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - uses: actions/checkout@v2

      - uses: xt0rted/dotnet-format-problem-matcher@v1.2.0

      - run: dotnet tool install -g dotnet-format

      - run: dotnet-format --check src
