name: SonarCloud Analysis

on:
  # Trigger analysis when pushing in master or pull requests, and when creating a pull request. 
  push:
    branches:
      - master
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build src --configuration Release

    - name: Test
      run: dotnet test src --configuration Release --no-build --nologo --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: src
        args: >
          -Dsonar.organization=laedit-github
          -Dsonar.projectKey=laedit_vika
          -Dsonar.cs.opencover.reportsPaths=NVika.Tests/coverage.opencover.xml
          -Dsonar.sources=NVika/
          -Dsonar.tests=NVika.Tests/
          -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}